config/routes.rb
KwTraining::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do
    resources :users
    resources :columnists do      
      resources :articles
    end
    resources :categories
    resources :organizations do
      resources :organization_images
    end
    resources :highlights
    resources :customers
    resources :enterprises do
      resources :portfolios
      
    end
    resources :statics, only: [:index]
    resources :tags
    resources :wikis
    resources :suggestions
    resources :enterprise_rates
    
    root to: 'statics#index'
  end
  
  resources :user_sessions, only: [:create, :new, :destroy]
  resources :users
  resources :searchs
  resources :profiles
  resources :comments do
    member do
      get :deletar
    end
  end
  resources :likes
  resources :blogs
  resources :categorias
  resources :suggestions
  resources :wiki
  resources :eventos
  resources :empresas do
    resources :rates
    member do
      get :tags
      get :filters
    end
  end
  
  resources :sobre
  resources :colunas do
    resources :artigos
  end
  
  resources :homes do
    collection do
      get :register
    end
  end
  
  resources :cadastro_empresas
  
  resources :authentications
  match '/auth/:provider/callback', to: 'authentications#create', via: :all
  
  root to: 'homes#index'  
  
  match 'blog', to: "blogs#index", via: :all
  match 'caixa-de-ideias', to: "suggestions#new", via: :all
  match 'perfil', to: "profiles#index", via: :all
  match 'register', to: "homes#register", via: :all
  match 'login', to: 'user_sessions#new', via: :all  
  match 'logout', to: 'user_sessions#destroy', via: :all
end

app/models/organization_image.rb
class OrganizationImage < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "226x260#", small: "50x50#" }
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

	belongs_to :organization, class_name: 'Admin::Organization'
end

app/controllers/admin/organization_images_controller.rb
class Admin::OrganizationImagesController < ApplicationController
   access_control do
    allow :administrator, :all
  end
  layout "admin"

  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_filter :load_father
  
  # GET /organization_images
  # GET /organization_images.json
  def index
    @organization_images = @organization.organization_images.all
  end

  # GET /organization_images/1
  # GET /organization_images/1.json
  def show

  end

  # GET /organization_images/new
  def new
    @organization_images = @organization.organization_images.build
  end

  # GET /organization_images/1/edit
  def edit

  end

  # POST /organization_images
  # POST /organization_images.json
  def create
    @organization_images = @organization.organization_images.build(image_params)
    @organization_images.organization_id = @organization.id
    @organization_images.save
    respond_to do |format|
      if @organization_images.save

        format.html { redirect_to admin_organization_organization_image_path(@organization, @organization_images), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: admin_organization_article_path(@organization, @organization_images) }
      else
        format.html { render :new }
        format.json { render json: @organization_images.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organization_images/1
  # PATCH/PUT /organization_images/1.json
  def update
    respond_to do |format|
      if @organization_images.update(image_params)
        
        format.html { redirect_to admin_organization_organization_image_path(@organization, @organization_images), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @organization_images] }
      else
        format.html { render :edit }
        format.json { render json: @organization_images.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /organization_images/1
  # DELETE /organization_images/1.json
  def destroy
    
    @organization_images.destroy
    respond_to do |format|
      format.html { redirect_to admin_organization_organization_images_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @organization_images = OrganizationImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:organization_image).permit(:title, :image)
    end


    def load_father
      @organization = Admin::Organization.find(params[:organization_id])
    end
end

app/helpers/admin/organization_images_helper.rb
module Admin::OrganizationImagesHelper
end

app/views/admin/organization_images/_form.html.haml
= form_for [@organization, @organization_images] do |f|
  -if f.error_messages
    .alert.alert-danger.alert-dismissable
      %i.fa.fa-ban
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %b Alert!
      Confira os campos marcados em vermelho.
  .box-body
    .form-group
      = f.label :title
      = f.text_field :title, :class => "form-control", :placeholder => "titulo" 
    
    .form-group
      = f.label :image
      = f.file_field :image, :class => "form-control"  
    - if @organization_images.image.file?
      .form-group
        =image_tag(@organization_images.image.url)
  
  .box-footer
    =f.submit nil, :class => "btn btn-primary" 

app/views/admin/organization_images/edit.html.haml
%section.content-header
  %h1
    Galeria de Fotos
    = "#{@organization.title}" 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => "/admin"}
        %i.fa.fa-dashboard
        Home
    %li
      %a{:href => "#{admin_organizations_path()}"}
        %i.fa.fa-dashboard
        Eventos
    %li.active Galeria de Fotos


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title Editar Artigo
        / /.box-header
        / form start
        = render 'form'
      

      %p
        = link_to t("back_list"), admin_organization_organization_images_path(@organization), :class => "btn btn-default"
        = link_to t("show"), admin_organization_organization_images_path(@organization, @organization_image), :class => "btn btn-default"

app/views/admin/organization_images/index.html.haml
%section.content-header
  %h1
    Galeria de Fotos
    = "#{@organization.title}" 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => "/admin"}
        %i.fa.fa-dashboard
        Home
    %li
      %a{:href => "#{admin_organizations_path()}"}
        %i.fa.fa-dashboard
        Eventos
    %li.active Galeria de Fotos
/ Main content
%section.content
  .col-xs-12
    %p
      = link_to "Nova Foto", new_admin_organization_organization_image_path, :class => "btn btn-primary" 
    
    .box
      .box-header
        %h3.box-title 
          Galeria de Fotos 
          
      .box-body.table-responsive.no-padding#tag_cloud

        /- tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class| 
        /  = link_to tag.name, admin_tag_path(tag.name), :class => css_class
        / - tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class|
        /   = link_to(tag.name, admin_tag_path(tag.name), :class => css_class)
      .box-body.table-responsive.no-padding
        %table.table.table-hover
          %tr
            %th=t("activerecord.attributes.article.title") 
            %th Imagem
            %th=t("actions")
          - for organization_image in @organization_images 
            %tr
              %td= organization_image.title 
              %td=""            
              %td 
                = link_to t("show"), admin_organization_organization_image_path(@organization, organization_image), :class => "btn btn-default"
                = link_to t("edit"), edit_admin_organization_organization_image_path(@organization, organization_image), :class => "btn btn-default"
                = link_to 'Destroy', admin_organization_organization_image_path(@organization, organization_image), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-default"

    %p
      = link_to "Novo Artigo", new_admin_organization_organization_image_path(@organization), :class => "btn btn-primary" 
      / = link_to "Ver Todos", admin_articles_path, :class => "btn btn-primary"  if !params[:tag].blank?

app/views/admin/organization_images/new.html.haml
%section.content-header
  %h1
    Galeria de Fotos
    = "#{@organization.title}" 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => "/admin"}
        %i.fa.fa-dashboard
        Home
    %li
      %a{:href => "#{admin_organizations_path()}"}
        %i.fa.fa-dashboard
        Eventos
    %li.active Galeria de Fotos


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title Nova Imagem
        / /.box-header
        / form start
        = render 'form'
      

      %p
        = link_to t("back_list"), admin_organization_organization_images_path(@organization), :class => "btn btn-default"

app/views/admin/organization_images/show.html.haml
%section.content-header
  %h1
    Galeria de Fotos
    = "#{@organization.title}" 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => "/admin"}
        %i.fa.fa-dashboard
        Home
    %li
      %a{:href => "#{admin_organizations_path()}"}
        %i.fa.fa-dashboard
        Eventos
    %li.active Galeria de Fotos
     

/ Main content
%section.content   
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title="#{@organization_images.title}"
        
        .box-body  
          %p
            %b= "Título"
            = @organization_images.title
        - if @organization_images.image.file?
          .box-body
            %p=image_tag(@organization_images.image.url)

  = link_to t("back_list"), admin_organization_organization_images_path, :class => "btn btn-default"
  = link_to t("edit"), edit_admin_organization_organization_image_path(@organization, @organization_images), :class => "btn btn-default" 
  = link_to "Nova Imagem", new_admin_organization_organization_image_path, :class => "btn btn-primary"