config/routes.rb
KwTraining::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do
    resources :users
    resources :columnists do      
      resources :articles
    end
    resources :categories
    resources :organizations do
      resources :organization_images
    end
    resources :highlights
    resources :customers
    resources :enterprises do
      resources :portfolios
      
    end
    resources :statics, only: [:index]
    resources :tags
    resources :wikis
    resources :suggestions
    resources :enterprise_rates
    
    root to: 'statics#index'
  end
  
  resources :user_sessions, only: [:create, :new, :destroy]
  resources :users
  resources :searchs
  resources :profiles
  resources :comments do
    member do
      get :deletar
    end
  end
  resources :likes
  resources :blogs
  resources :categorias
  resources :suggestions
  resources :wiki
  resources :eventos
  resources :empresas do
    resources :rates
    member do
      get :tags
      get :filters
    end
  end
  
  resources :sobre
  resources :colunas do
    resources :artigos
  end
  
  resources :homes do
    collection do
      get :register
    end
  end
  
  resources :cadastro_empresas
  
  resources :authentications
  match '/auth/:provider/callback', to: 'authentications#create', via: :all
  
  root to: 'homes#index'  
  
  match 'blog', to: "blogs#index", via: :all
  match 'caixa-de-ideias', to: "suggestions#new", via: :all
  match 'perfil', to: "profiles#index", via: :all
  match 'register', to: "homes#register", via: :all
  match 'login', to: 'user_sessions#new', via: :all  
  match 'logout', to: 'user_sessions#destroy', via: :all
end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_taggable_on :tags
  
  has_attached_file :image_article
  validates_attachment :image_article, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  
  has_and_belongs_to_many :category
  belongs_to :columnist, class_name: 'Admin::Columnist'
  has_many :article_reads
  
  validates_presence_of :title
  validates_presence_of :subtitle
  validates_presence_of :description
  validates_presence_of :image_article

  # def self.search(search)
  #   if search
  #     find(:all, :conditions => ['published =  true and active = true and (title LIKE ? or subtitle LIKE ? or description LIKE ?)', "%#{search}%", "%#{search}%", "%#{search}%"])
  #   else
  #     find(:all)
  #   end
  # end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  access_control do
    allow :administrator, :all
  end
  layout "admin"

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_filter :load_categories, :load_father
  # GET /articles
  # GET /articles.json
  def index
    @articles = @columnist.articles.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = @columnist.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = @columnist.articles.build(article_params)
    @article.columnist_id = @columnist.id
    @article.save
    respond_to do |format|
      if @article.save
        
        #INSERIR NO FEED
        save_or_update_feed(@article.id)

        format.html { redirect_to admin_columnist_article_path(@columnist, @article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: admin_columnist_article_path(@columnist, @article) }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        
        #INSERIR NO FEED
        save_or_update_feed(@article.id)
        
        format.html { redirect_to admin_columnist_article_path(@columnist, @article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @article] }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    
    feeds = Feed.where(["object_type = ? AND object_id = ?", "post", @article.id])
    
    #feeds.each do f
    #  f.destroy
    #end
    
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_columnist_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def save_or_update_feed(object_id)
      check = Feed.where(["object_id = ?", object_id])
      
      if check.empty?
        feed = Feed.new
      else
        feed = Feed.find(check.first.id)
      end

      feed.object_id = object_id
      feed.object_type = "post"
      feed.save
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :subtitle, :description, :ordem, :active, :published, :tag_list, :image_article, :columnist_id, :position, category_ids: [])
    end

    def load_categories
      @categories = Category.where("published = true").all.collect { |c| [c.name, c.id] }
      # @categories = Admin::Category.includes(:children).where("admin_categories.published = true").all
    end

    # def load_columnists
    #   @columnists = Admin::Columnist.where("published = true").all.collect { |c| [c.name, c.id] }
    # end

    def load_father
      @columnist = Admin::Columnist.find(params[:columnist_id])
    end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.haml
= form_for [@columnist, @article] do |f|
  -if f.error_messages
    .alert.alert-danger.alert-dismissable
      %i.fa.fa-ban
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %b Alert!
      Confira os campos marcados em vermelho.
  .box-body
    .form-group
      = f.label :title
      = f.text_field :title, :class => "form-control", :placeholder => "titulo" 
    .form-group
      = f.label :subtitle
      = f.text_field :subtitle, :class => "form-control", :placeholder => "subtitulo"
    .form-group 
      = f.label :description
      = f.text_area :description, :class => "form-control ckeditor", :placeholder => "descrição"
    .form-group 
      = f.label :category_ids, "Escolha a Categoria"    
      = f.select :category_ids, @categories,{}, {multiple: "multiple", class: "form-control select2"}
    .form-group 
      = f.label :position, "Escolha a posição"
      %br
      = f.select :position, options_for_select([["Destaque", "1"], ["Destaque Direita", "2"], ["Baixo", "3"]], @article.position),{}, {class: "form-control select2"}
    / .form-group 
    /   = f.label :columnist_id, "Escolha o Colunista"    
    /   = f.select :columnist_id, @columnists,{}, {class: "form-control select2"}
    .form-group
      = f.label :tag_list
      = f.text_field :tag_list, :class => "form-control tags", :placeholder => "Tags"  
    .form-group 
      = f.label :ordem
      = f.number_field :ordem, :class => "form-control"
    .form-group 
      = f.label :published
      = f.check_box :published
    .form-group
      = f.label :image_article
      = f.file_field :image_article, :class => "form-control"  
    - if @article.image_article.file?
      .form-group
        =image_tag(@article.image_article.url)
  .box-footer
    =f.submit nil, :class => "btn btn-primary" 

-content_for :footer do
  :javascript
    $(function () {
      $(".select2").select2();
    });

app/views/admin/articles/edit.html.haml
%section.content-header
  %h1
    Artigos
    ="#{@columnist.name}"
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => "#"}
        %i.fa.fa-dashboard
        Home
    %li.active Artigos


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title Editar Artigo
        / /.box-header
        / form start
        = render 'form'
      

      %p
        = link_to t("back_list"), admin_columnist_articles_path, :class => "btn btn-default"
        = link_to t("show"), admin_columnist_article_path(@columnist, @article), :class => "btn btn-default"

app/views/admin/articles/index.html.haml
%section.content-header
  %h1
    Artigos
    = "#{@columnist.name}" 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => "/admin"}
        %i.fa.fa-dashboard
        Home
    %li
      %a{:href => "#{admin_columnists_path()}"}
        %i.fa.fa-dashboard
        Colunistas
    %li.active Artigos
/ Main content
%section.content
  .col-xs-12
    %p
      = link_to "Novo Artigo", new_admin_columnist_article_path, :class => "btn btn-primary" 
      / = link_to "Ver Todos", admin_articles_path, :class => "btn btn-primary"  if !params[:tag].blank?
    
    .box
      .box-header
        %h3.box-title 
          Artigos Cadastrados
          = " - Com Tag '#{params[:tag]}'" if !params[:tag].blank? 
          
      .box-body.table-responsive.no-padding#tag_cloud

        /- tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class| 
        /  = link_to tag.name, admin_tag_path(tag.name), :class => css_class
        / - tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class|
        /   = link_to(tag.name, admin_tag_path(tag.name), :class => css_class)
      .box-body.table-responsive.no-padding
        %table.table.table-hover
          %tr
            %th=t("activerecord.attributes.article.title") 
            %th=t("activerecord.attributes.article.subtitle")
            %th Colunista
            / %th=t("activerecord.attributes.article.tag_list")                         
            %th=t("activerecord.attributes.article.order")
            %th=t("activerecord.attributes.article.active")
            %th=t("actions")
          - for article in @articles 
            %tr
              %td= article.title 
              %td= article.subtitle
              %td= @columnist.name
              / %td= raw article.tag_list.map{ |t| link_to t, admin_tag_path(t)}.join(', ')                            
              %td= article.ordem
              %td= article.active              
              %td 
                = link_to t("show"), admin_columnist_article_path(@columnist, article), :class => "btn btn-default"
                = link_to t("edit"), edit_admin_columnist_article_path(@columnist, article), :class => "btn btn-default"
                = link_to 'Destroy', admin_columnist_article_path(@columnist, article), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-default"

    %p
      = link_to "Novo Artigo", new_admin_columnist_article_path, :class => "btn btn-primary" 
      / = link_to "Ver Todos", admin_articles_path, :class => "btn btn-primary"  if !params[:tag].blank?

app/views/admin/articles/new.html.haml
%section.content-header
  %h1
    Artigo
    = "#{@columnist.name}" 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => "#"}
        %i.fa.fa-dashboard
        Home
    %li.active Artigo


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title Novo Artigo
        / /.box-header
        / form start
        = render 'form'
      

      %p
        = link_to t("back_list"), admin_columnist_articles_path, :class => "btn btn-default"

app/views/admin/articles/show.html.haml
%section.content-header
  %h1
    Artigos
    = "#{@columnist.name}"
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => "#"}
        %i.fa.fa-dashboard
        Home
    %li
      %a{:href => "#{admin_columnists_path()}"}
        %i.fa.fa-dashboard
        Colunistas
    %li.active Artigos
     

/ Main content
%section.content   
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title="#{@article.title}"
        
        .box-body  
          %p
            %b= "#{t("activerecord.attributes.article.subtitle")}: "
            = @article.subtitle   
        .box-body  
          %p
            %b= "#{t("activerecord.attributes.article.description")}:"
            %br
            = raw @article.description   
        .box-body  
          %p
            %b= "#{t("activerecord.attributes.article.order")}: "
            = @article.ordem   
        .box-body  
          %p
            %b= "#{t("activerecord.attributes.article.tag_list")}: "
            = @article.tag_list
        .box-body  
          %p
            %b= "#{t("activerecord.attributes.article.published")}: "
            = @article.published
        - if @article.image_article.file?
          .box-body
            %p=image_tag(@article.image_article.url)

  = link_to t("back_list"), admin_columnist_articles_path, :class => "btn btn-default"
  = link_to t("edit"), edit_admin_columnist_article_path(@columnist, @article), :class => "btn btn-default" 
  = link_to "Novo Artigo", new_admin_columnist_article_path, :class => "btn btn-primary"