config/routes.rb
KwTraining::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do
    resources :users
    resources :columnists do      
      resources :articles
    end
    resources :categories
    resources :organizations do
      resources :organization_images
    end
    resources :highlights
    resources :customers
    resources :enterprises do
      resources :portfolios
      
    end
    resources :statics, only: [:index]
    resources :tags
    resources :wikis
    resources :suggestions
    resources :enterprise_rates
    
    root to: 'statics#index'
  end
  
  resources :user_sessions, only: [:create, :new, :destroy]
  resources :users
  resources :searchs
  resources :profiles
  resources :comments do
    member do
      get :deletar
    end
  end
  resources :likes
  resources :blogs
  resources :categorias
  resources :suggestions
  resources :wiki
  resources :eventos
  resources :empresas do
    resources :rates
    member do
      get :tags
      get :filters
    end
  end
  
  resources :sobre
  resources :colunas do
    resources :artigos
  end
  
  resources :homes do
    collection do
      get :register
    end
  end
  
  resources :cadastro_empresas
  
  resources :authentications
  match '/auth/:provider/callback', to: 'authentications#create', via: :all
  
  root to: 'homes#index'  
  
  match 'blog', to: "blogs#index", via: :all
  match 'caixa-de-ideias', to: "suggestions#new", via: :all
  match 'perfil', to: "profiles#index", via: :all
  match 'register', to: "homes#register", via: :all
  match 'login', to: 'user_sessions#new', via: :all  
  match 'logout', to: 'user_sessions#destroy', via: :all
end

app/controllers/admin/enterprises_controller.rb
class Admin::EnterprisesController < ApplicationController
  layout "admin"
  before_action :set_admin_enterprise, only: [:show, :edit, :update, :destroy]
  before_filter :load_specialities
  access_control do
      allow :administrator, :all
  end
  # GET /admin/enterprises
  # GET /admin/enterprises.json
  def index
    @admin_enterprises = Admin::Enterprise.all.order(:created_at => "DESC")
  end

  # GET /admin/enterprises/1
  # GET /admin/enterprises/1.json
  def show
  end

  # GET /admin/enterprises/new
  def new
    @admin_enterprise = Admin::Enterprise.new
  end

  # GET /admin/enterprises/1/edit
  def edit
  end

  # POST /admin/enterprises
  # POST /admin/enterprises.json
  def create
    @admin_enterprise = Admin::Enterprise.new(admin_enterprise_params)

    respond_to do |format|
      if @admin_enterprise.save
        format.html { redirect_to @admin_enterprise, notice: 'Enterprise was successfully created.' }
        format.json { render :show, status: :created, location: @admin_enterprise }
      else
        format.html { render :new }
        format.json { render json: @admin_enterprise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/enterprises/1
  # PATCH/PUT /admin/enterprises/1.json
  def update
    respond_to do |format|
      if @admin_enterprise.update(admin_enterprise_params)
        format.html { redirect_to @admin_enterprise, notice: 'Enterprise was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_enterprise }
      else
        format.html { render :edit }
        format.json { render json: @admin_enterprise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/enterprises/1
  # DELETE /admin/enterprises/1.json
  def destroy
    @admin_enterprise.destroy
    respond_to do |format|
      format.html { redirect_to admin_enterprises_url, notice: 'Enterprise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_enterprise
      @admin_enterprise = Admin::Enterprise.find(params[:id])
    end
    
    def load_specialities
      @specialities = Speciality.all.collect { |c| [c.name, c.id] }
      # @categories = Admin::Category.includes(:children).where("admin_categories.published = true").all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_enterprise_params
      params.require(:admin_enterprise).permit!
      #params.require(:admin_enterprise).permit(:name, :description, :img_enterprise, :banner_enterprise, :specialties, :tag_list, :address, :number, :phone, :email, :site, :featured, :city, :state, :published, speciality_ids: [])
    end
end

app/helpers/admin/enterprises_helper.rb
module Admin::EnterprisesHelper
end

app/views/admin/enterprises/_form.html.haml
= form_for @admin_enterprise do |f|
  -if f.error_messages
    .alert.alert-danger.alert-dismissable
      %i.fa.fa-ban
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %b Alert!
      Confira os campos marcados em vermelho.

  .box-body
    .form-group
      =t('activerecord.attributes.admin_enterprise.name')      
      = f.text_field :name, :class => "form-control", :placeholder => "Preencha o nome"
    .form-group
      =t('activerecord.attributes.admin_enterprise.description')
      = f.text_area :description, :class => "form-control", :placeholder => "descrição"
      
    .form-group
      ="Endereço"
      = f.text_field :address, :class => "form-control", :placeholder => "Endereço"
      
    .form-group
      ="Cidade"
      = f.text_field :city, :class => "form-control", :placeholder => "Cidade"
      
    .form-group
      ="Estado"
      = f.text_field :state, :class => "form-control", :placeholder => "Estado"
      
    .form-group
      ="Número"
      = f.text_field :number, :class => "form-control", :placeholder => "Número"
      
    .form-group
      ="Phone"
      = f.text_field :phone, :class => "form-control", :placeholder => "Telefone"
      
    .form-group
      ="E-mail"
      = f.text_field :email, :class => "form-control", :placeholder => "E-mail"

    .form-group
      ="Site"
      = f.text_field :site, :class => "form-control", :placeholder => "Site"
    
    .form-group
      ="Empresa em destaque?"
      = f.check_box :featured
  
    
    .form-group
      = f.label :tag_list, "Tags"
      = f.text_field :tag_list, :class => "form-control tags", :placeholder => "Tags"
    
    .form-group
      = f.label :speciality_ids, "Selecione até 5 produtos:"
      %br
      = f.collection_select(:speciality_ids, Speciality.all, :id, :name, {}, {multiple: "multiple", class: "form-control select2"})
      
                                                                                                               
    /.form-group
    /  = f.label :speciality_ids, "Especialidades"
    /  %br
    /  = f.collection_check_boxes(:speciality_ids, Speciality.all, :id, :name)
    /.form-group
    /  =f.label :specialties, "Especialidades"
    /  %select.select2.form-control#user_services_performed{name: "admin_enterprise[specialties]", multiple: "multiple"}
    /    %option{:value => "4"}Análise de Negócios
    /    %option{:value => "5"}Apresentações
    /    %option{:value => "6"}Atendimento ao Cliente
    /    %option{:value => "7"}Avaliação de Desempenho
    /    %option{:value => "8"}Centros de Eventos
    /    %option{:value => "9"}Clima Organizacional
    /    %option{:value => "10"}Cloud Computing
    /    %option{:value => "11"}Coaching
    /    %option{:value => "12"}Compliance
    /    %option{:value => "13"}Comunicação
    /    %option{:value => "14"}Consultoria em Gestão Educacional
    /    %option{:value => "15"}Criatividade
    /    %option{:value => "16"}Cultura Organizacional
    /    %option{:value => "17"}Desenv. de Aplicativos Móveis
    /    %option{:value => "18"}Desenvolvimento de Carreiras
    /    %option{:value => "19"}Desenvolvimento Organizacional
    /    %option{:value => "20"}Design Gráfico
    /    %option{:value => "21"}Direção Defensiva
    /    %option{:value => "22"}Diversidade
    /    %option{:value => "23"}EAD e-Learning
    /    %option{:value => "24"}EAD Plataforma Mobile
    /    %option{:value => "25"}Etiqueta Corporativa
    /    %option{:value => "26"}Finanças para não Financeiros
    /    %option{:value => "27"}Formação de Treinadores
    /    %option{:value => "28"}Gestão da Mudança
    /    %option{:value => "29"}Gestão da Performance
    /    %option{:value => "30"}Gestão de Compras
    /    %option{:value => "31"}Gestão de Conflitos
    /    %option{:value => "32"}Gestão de Contratos
    /    %option{:value => "33"}Gestão de Equipes
    /    %option{:value => "34"}Gestão de Grandes Contas (KAM)
    /    %option{:value => "35"}Gestão de Projetos
    /    %option{:value => "36"}Gestão de Riscos
    /    %option{:value => "37"}Gestão de Riscos Financeiros
    /    %option{:value => "38"}Gestão do Comportamento Organizacional
    /    %option{:value => "39"}Gestão do Stress
    /    %option{:value => "40"}Gestão do Tempo
    /    %option{:value => "41"}Gestão Estratégica
    /    %option{:value => "42"}Gestão por Competências
    /    %option{:value => "43"}Idiomas
    /    %option{:value => "44"}Inclusão Social
    /    %option{:value => "45"}Inovação
    /    %option{:value => "46"}Jogos Corporativos
    /    %option{:value => "47"}Licitações
    /    %option{:value => "48"}Liderança
    /    %option{:value => "49"}Logística de Treinamento
    /    %option{:value => "50"}Manuais de Treinamento
    /    %option{:value => "51"}Mapa Mental
    /    %option{:value => "52"}Materiais Gráficos
    /    %option{:value => "53"}Mensuração de Resultados
    /    %option{:value => "54"}Mídias Sociais
    /    %option{:value => "55"}Multi mídia
    /    %option{:value => "56"}Negociação
    /    %option{:value => "57"}Negócios Internacionais
    /    %option{:value => "58"}Neurociência
    /    %option{:value => "59"}Neurolinguística
    /    %option{:value => "60"}Palestras
    /    %option{:value => "61"}Produtividade
    /    %option{:value => "62"}Recrutamento e Seleção
    /    %option{:value => "63"}ROI de Treinamento
    /    %option{:value => "64"}Salas para Treinamento
    /    %option{:value => "65"}Secretariado Executivo
    /    %option{:value => "66"}Segurança em TI
    /    %option{:value => "67"}Seguros
    /    %option{:value => "68"}Serviço ao Cliente
    /    %option{:value => "69"}Servidores e Rede
    /    %option{:value => "70"}Sistemas Operacionais em TI
    /    %option{:value => "71"}Six Sigma
    /    %option{:value => "72"}Supply Chain
    /    %option{:value => "73"}Taxas
    /    %option{:value => "74"}Team Building
    /    %option{:value => "75"}Treinamento de Vendas
    /    %option{:value => "76"}Visão, Missão e Valores
    /    %option{:value => "77"}Voluntariado
    /    %option{:value => "78"}Web Design
    /    %option{:value => "79"}Windows Office
    /    %optgroup{:label => "Leis"}
    /      %option{:value => "81"}Direito Civil
    /      %option{:value => "82"}Direito Empresarial
    /      %option{:value => "83"}Direito Internacional
    /      %option{:value => "84"}Direito Trabalhista
    /      %option{:value => "85"}Direito Tributário
    /    %optgroup{:label => "Engenharia"}
    /      %option{:value => "87"}Segurança do Trabalho
    /      %option{:value => "88"}Brigada de Incêndio
    /      %option{:value => "89"}ISO 9001
    /    %optgroup{:label => "Saúde"}
    /    %optgroup{:label => "Finanças"}
    /      %option{:value => "92"}Administração Tributária
      
      

    .form-group
      = f.label :img_enterprise
      = f.file_field :img_enterprise, :class => "form-control"  
    - if @admin_enterprise.img_enterprise.file?
      .form-group
        =image_tag(@admin_enterprise.img_enterprise.url(:medium))
    .form-group
      = f.label :banner_enterprise
      = f.file_field :banner_enterprise, :class => "form-control"  
    - if @admin_enterprise.banner_enterprise.file?
      .form-group
        =image_tag(@admin_enterprise.banner_enterprise.url(:medium))
        
    .form-group
      = f.label :published,  "Publicada?"
      = f.check_box :published
    
  .box-footer
    =f.submit "Salvar", :class => "btn btn-primary"

-content_for :footer do
  :javascript
    $(function () {
      $(".select2").select2({
        maximumSelectionLength: 5
      });
    });

app/views/admin/enterprises/edit.html.haml
%section.content-header
  %h1
    Empresas
    %small Control panel
  %ol.breadcrumb
    %li
      %a{:href => "/admin"}
        %i.fa.fa-dashboard
        Home
    %li.active Empresas


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title Editar Empresa
        / /.box-header
        / form start
        = render 'form'
      

      %p
        = link_to "Back to List", admin_enterprises_path, :class => "btn btn-default"

app/views/admin/enterprises/index.html.haml
%section.content-header
  %h1
    Empresas  
    %small Control panel
  %ol.breadcrumb
    %li
      %a{:href => "/admin"}
        %i.fa.fa-dashboard
        Home
    %li.active Empresas


/ Main content
%section.content
  .col-xs-12
    %p= link_to "Nova Empresa", new_admin_enterprise_path, :class => "btn btn-primary"
    
    .box.a
      .box-header
        %h3.box-title Empresas
        
      / /.box-header
      .box-body.table-responsive.no-padding
        %table.table.table-hover
          %tr
            %th ID
            %th=t("activerecord.attributes.admin_enterprise.name")
            %th=t("activerecord.attributes.admin_enterprise.description")
            %th=t("activerecord.attributes.admin_enterprise.visualizations")
            %th="Publicada?"
            %th Ações
          - @admin_enterprises.each do |admin_enterprise|
            %tr{:style => ("background-color:#f39c12;" unless admin_enterprise.published?)}
              %td= admin_enterprise.id
              %td= admin_enterprise.name
              %td= admin_enterprise.description
              %td= admin_enterprise.visualizations
              %td= admin_enterprise.published
              %td 
                = link_to "Show", [admin_enterprise], :class => "btn btn-default"
                = link_to "Edit", edit_admin_enterprise_path(admin_enterprise), :class => "btn btn-default"
                = link_to "Portifolios", admin_enterprise_portfolios_path(admin_enterprise), :class => "btn btn-primary"
                = link_to "Destroy", [admin_enterprise], :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-danger"

    %p= link_to "Nova Empresa", new_admin_enterprise_path, :class => "btn btn-primary"

app/views/admin/enterprises/new.html.haml
%section.content-header
  %h1
    Empresas
    %small Control panel
  %ol.breadcrumb
    %li
      %a{:href => "/admin"}
        %i.fa.fa-dashboard
        Home
    %li.active Empresas


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title Nova Empresas
        / /.box-header
        / form start
        = render 'form'
      

      %p
        = link_to "Back to List", admin_enterprises_path, :class => "btn btn-default"

app/views/admin/enterprises/show.html.haml
%section.content-header
  %h1
    Empresas  
    %small Control panel
  %ol.breadcrumb
    %li
      %a{:href => "/admin"}
        %i.fa.fa-dashboard
        Home
    %li.active Empresas
     

/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title="#{@admin_enterprise.name}"
        
        .box-body  
          %p= "Descrição: #{@admin_enterprise.description}"

        .box-body  
          %p= "Visualizações: #{@admin_enterprise.visualizations}"
            


  = link_to "Edit", edit_admin_enterprise_path(@admin_enterprise), :class => "btn btn-default"
  = link_to "View All", admin_enterprises_path, :class => "btn btn-default"